version: "3"
services:
  roleplay:
    container_name: ropleplay
    build:
      context: "./"
      dockerfile: "Dockerfile.roleplay"
    environment:
      - NODE_ENV=development
    volumes:
      - "./:/app"
    command: npm run dev
    restart: unless-stopped
    ports:
      - "3333:3333"
    networks:
      - roleplay-network

  mysql-roleplay:
    image: 'mysql/mysql-server:8.0'
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-roleplay
    ports:
      - '3307:3307'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: roleplay
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - roleplay-network

networks:
  roleplay-network:
    driver: bridge
